# -*- coding: utf-8 -*-
"""Escape Character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7R4CEbwLHzR6fqO2AZl9-qI2a2zEDE2
"""

print("Dia berkata:'Pergilah!'")

print("Aku menimpali:\"Apakah kau ingin aku'angkat kaki'?!\"")

print("\\(^_^)/ (\\-_-/)")