# -*- coding: utf-8 -*-
"""Manipulsi String-Meylani-074.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z7lDnZIbvG956nf4-5TB2W-3d3n4Hg2k
"""

nama = 'Meylani Eka Sabila'
asal = "Indonesia"

print(nama)

print(asal)

"""**Manipulasi String**"""

print(nama,asal)

print(nama + asal)

print("Halo, nama saya", nama)

print("Halo, nama saya", nama, " asal saya dari", asal)

print(data_lengkap)

nama = 'Meylani Eka Sabila'
asal = "Indonesia"

print(nama)
print(asal)
print(nama, asal)

"""**String + Non String**"""

asal_kota = "Bandar Lampung"
kode_pos = 35144

asal_kota_kode_pos = asal_kota + str(kode_pos)

print(asal_kota_kode_pos)

asal_kota_x5 = asal_kota * 5
print(asal_kota_x5)