# -*- coding: utf-8 -*-
"""Manipulasi String 3- Meylani-074.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eCdgMfx5z4mzlw4IXDTZUbq8LaZb-YY8

*   Nama: Meylani Eka Sabila
*   NPM: 2411012074
"""

template = 'Halo, saya %s dari %s'
print(template %('Ledis Fabri', 'Indonesia'))

template = "Halo, saya {nama} dari {asal}"
template_2 = "Saya suka makan {} dan minum {}"

print(template.format(nama='Meylani', asal='Bandar Lampung'))
print(template_2.format('Nasi Padang', 'Ice Lemon Tea'))

nama = 'Meylani'
asal = 'Lampung'

print('Perkenalan saya Meylani dari Lampung')

alamat = 'Surabaya, Jawa Timur, Indonesia'

print(alamat.split())
print(alamat,split(','))
print(alamat.split(', '))

print(' '.join(['aku', 'suka', 'python']))
print(' '.join(alamat.split(', ')))

print('Halo selamat pagi!'.upper())
print('Halo Selamat Siang!'.upper())

print('APA KABAR?'.lower())
print('Lagi Dimana?'.lower())

print('daun tidak pernah membenci angin'.title())
print('LASKAR PELANGI'.title())

print("Indonesia Adalah Negara Kepulauan". swapcase())
print("aKu cInTa NeGeRiKu". swapcase())

angka="12345"

print('Index angka 3:', angka.find ('3'))
print('Index angka 45:', angka.find ('45'))
print('Index angka 35:', angka.find ('35'))

ibu_kota = "Jakarta"
print(ibu_kota. replace('a', 'i'))
print(ibu_kota.replace('kar', '👾'))

ibu_kota = "Jakarta"
print(ibu_kota. replace('a', ''))

paragraf = 'Baru-baru ini telat ditemukan sebuah meteor di suatu laut'
x = paragraf.count('di')
print(f'kata "di" muncul sebanyak {x} kali')