# -*- coding: utf-8 -*-
"""Manipulasi String 2- Meylani- 074.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LEA9ndo2dQ2gLPduAp9edMeFjAKDT36v

*   Nama: Meylani Eka Sabila
*   NPM: 2411012074

**Operasi in Pada String**
"""

#Berfungsi untuk mencari apakah suatu karakter kata terdapat pada sebuah string.

berita = "Ramai ramai developer di seluruh dunia mulai menggunakan teks editor masa kini seperti Visual Studio Code, atom, sublime text, dan lain sebagainya."
print('sublime text'in berita )
print('notepad++'in berita)

kalimat = "Meylani suka makan dimsum mentai"
print("dimsum" in kalimat)
print("batagor" in kalimat)

"""**Memotong String**"""

Nama = "Meylani Eka Sabila"

print(Nama [3])
print(Nama [10])
print(Nama [16])
print(Nama [-1])

"""**Slicing String**"""

Kalimat = "Computer Programming Mata Kuliah Yang Menyenangkan"
print(Kalimat [0:8])
print(Kalimat [8:21])
print(Kalimat [21:25])
print(Kalimat [25:32])
print(Kalimat [32:37])
print(Kalimat [37:50])
print(Kalimat [0:50])

"""**Menghitung Panjang String**"""

print(len("Meylani Eka Sabila"))
print(len("Mahasiswi Bisnis Digital"))
print(len("Universitas Lampung"))

"""**Memeriksa Karakter Awal String**"""

Nomor_telepon_1 = "08123679372857624"
Nomor_telepon_2 = "62865381975319735"
Nomor_telepon_3 = "+6281356769878908"

Kode_negara = "+62"
print(Nomor_telepon_1.startswith(Kode_negara))
print(Nomor_telepon_2.startswith(Kode_negara))
print(Nomor_telepon_3.startswith(Kode_negara))

"""**Memeriksa Karakter Akhir String**"""

email_1 = "meylanieka795@gmail.com"
emial_2 = "meylanoeka795@outlook.com"

print(email_1.endswith("gmail.com"))
print(email_2.endswith("gmail.com"))