# -*- coding: utf-8 -*-
"""Tipe Data Casting-Meylani-074.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JP1-Gvk6VQqTOPArr24lj8wck0ZyCYRP

*  Nama : Meylani Eka Sabila
*  NPM  : 2411012074
"""

nama = 'budi'
usia = 20
lajang = True

print(type(nama))
print(type(usia))
print(type(lajang))

#Konversi Tipe Data

usia = input("Masukan usia anda:")
print(type(usia))

# Yang Salah

panjang = input("Masukan panjnag:")
lebar = input("Masukan lebar:")
print ('Luas =', panjang * lebar)

# Yang Benar

panjang = int(input("Masukan panjang:"))
lebar = float(input("Masukan lebar:"))
print ('Luas =', panjang * lebar)

nama = 'mey '
tahun_lahir = 2006
print(nama + 'lahir di tahun' + " " + str(tahun_lahir))

a = 10/2
b = 1/2

print(type(a))
print(type(b))